[package]
name = "sparkler_gen_graph_sketch"
version = "0.1.0"
edition = "2024"

[dependencies]
sparkler = { path = "../sparkler" }
shared = { path = "../shared" }

[lints]
workspace = true

[build-dependencies]
spirv-builder = { git = "https://github.com/rust-gpu/rust-gpu", branch = "main" }
