[package]
name = "sparkler_builder"
version = "0.1.0"
edition = "2024"


[dependencies]
syn = { version = "2", features = ["full", "extra-traits"] }
quote = "1"
spirv-builder = { git = "https://github.com/rust-gpu/rust-gpu", branch = "main" }


[lints]
workspace = true
