name: Native GPU

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  RUST_BACKTRACE: 1

jobs:
  macos-metal:
    name: macOS Metal
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        
      - name: Cache dependencies
        uses: Swatinem/rust-cache@v2
          
      - name: Run the demo (Metal)
        run: cargo run --release --features wgpu
        
      - name: Run unit tests
        run: cargo test --release --features wgpu

  windows-directx:
    name: Windows DirectX
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        
      - name: Cache dependencies
        uses: Swatinem/rust-cache@v2
          
      - name: Run the demo (DirectX/HLSL)
        run: cargo run --release --features wgpu
        
      - name: Run unit tests
        run: cargo test --release --features wgpu

  linux-llvmpipe-wgpu:
    name: Linux LLVMpipe (wgpu)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        
      - name: Install xvfb, llvmpipe and lavapipe
        run: |
          sudo apt-get update -y -qq
          sudo add-apt-repository ppa:kisak/turtle -y
          sudo apt-get update
          sudo apt install -y xvfb libgl1-mesa-dri libxcb-xfixes0-dev mesa-vulkan-drivers
          
      - name: Cache dependencies
        uses: Swatinem/rust-cache@v2
          
      - name: Set LLVMpipe environment
        run: |
          echo "VK_ICD_FILENAMES=/usr/share/vulkan/icd.d/lvp_icd.x86_64.json" >> $GITHUB_ENV
          
      - name: Run the demo (wgpu)
        run: cargo run --release --features wgpu
        
      - name: Run unit tests (wgpu)
        run: cargo test --release --features wgpu

  linux-llvmpipe-ash:
    name: Linux LLVMpipe (ash)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        
      - name: Install xvfb, llvmpipe and lavapipe
        run: |
          sudo apt-get update -y -qq
          sudo add-apt-repository ppa:kisak/turtle -y
          sudo apt-get update
          sudo apt install -y xvfb libgl1-mesa-dri libxcb-xfixes0-dev mesa-vulkan-drivers
          
      - name: Cache dependencies
        uses: Swatinem/rust-cache@v2
          
      - name: Set LLVMpipe environment
        run: |
          echo "VK_ICD_FILENAMES=/usr/share/vulkan/icd.d/lvp_icd.x86_64.json" >> $GITHUB_ENV
          
      - name: Run the demo (ash)
        run: cargo run --release --features ash
        
      - name: Run unit tests (ash)
        run: cargo test --release --features ash
